### PR TITLE
added a notes website

### PR DESCRIPTION
**Pull request by SahilS1G**

### CODE REVIEW

**Comment by varunKT001** [comment]
@SahilS1G 

I already told you that you must create a unique project to get it merged into this repository. Please don't spam!

**Comment by SahilS1G** [comment]
ohh i am really sorry 
this was my first pull request i thought  i was doing something wrong so i tried to do it again

**Comment by SahilS1G** [comment]
> @SahilS1G
> 
> I already told you that you must create a unique project to get it merged into this repository. Please don't spam!
i am really sorry

**Comment by SahilS1G** [comment]
> 
> 
> I already told you that you must create a unique project to get it merged into this repository. Please don't spam!

@varunKT001 will you please remove the spam label 
it was a rookie mistake

**Comment by varunKT001** [comment]
@SahilS1G Ok, no issue 👍

**Pull request closed without merging**
