### PR TITLE
added new js project

### PR DESCRIPTION
**Pull request by PathakTushar**
added new project made with HTML,CSS,JS

### CODE REVIEW

**Comment by varunKT001** [comment]
@PathakTushar 

Please write a brief description of what your project is all about. Also, next time, please try to follow the PR template properly.

**Review by varunKT001 — COMMENTED** [review]
@PathakTushar

Please write a brief description of what your project is all about. Also, next time, please try to follow the PR template properly.

**Comment by PathakTushar** [comment]
This project is simply a dice game whose rules has been mentioned under the rules button of the game.

**Comment by varunKT001** [comment]
@PathakTushar Why is it named `Pig-game` then?

**Comment by PathakTushar** [comment]
Because this game is called pig game only. You can google about it.

**Review by varunKT001 — APPROVED** [review]
LGTM @PathakTushar 
Thanks for your contribution!
Don't forget to star this repository 😄

**Pull request merged**
