### PR TITLE
Gym Website Added

### PR DESCRIPTION
**Pull request by ravish036**
**Issue reference:**
#49 

**Proposed changes:**
Added the files.

Please delete options that are not relevant.

- [x] Other (Project files added)

**Checklist:**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

**Additional info (if any):**

Consider this under Hackoctoberfest'22.

### CODE REVIEW

**Comment by varunKT001** [comment]
@ravish036 

Please move all the images to a separate directory.

**Review by varunKT001 — CHANGES_REQUESTED** [review]
@ravish036

Please move all the images to a separate directory.

**Comment by ravish036** [comment]
@varunKT001 okay..

**Review by varunKT001 — CHANGES_REQUESTED** [review]
@ravish036 

Remove the `.vscode` folder.

**Comment by ravish036** [comment]
@varunKT001 
Done 👍🏻👍🏻

**Review by ravish036 — COMMENTED** [review]
Done the required changes

**Review by varunKT001 — APPROVED** [review]
LGTM @ravish036 
Thanks for your contribution!
Don't forget to star the repository 😄

**Pull request merged**
