### PR TITLE
added styling and products

### PR DESCRIPTION
**Pull request by anuragasawa20**
#50 issue resolved

**Proposed changes:**

**Type of change:**

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

**Checklist:**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

**Additional info (if any):**

### CODE REVIEW

**Comment by anuragasawa20** [comment]
Sir please have a look at changes. If need to more improve assist me.

**Review by varunKT001 — CHANGES_REQUESTED** [review]
@anuragasawa20 

Please remove the commented code from `index.html`.

**Review by varunKT001 — APPROVED** [review]
LGTM @anuragasawa20 
Thanks for your contribution!
Don't forget to star the repository 😄

**Comment by anuragasawa20** [comment]
Sure Sir thank you very much for accepting PR.

**Pull request merged**
