### PR TITLE
RGB-TO-HEX-CONVERTER

### PR DESCRIPTION
**Pull request by ravish036**
**Issue reference:**
#52 
**Proposed changes:**
Added the required files

Please delete options that are not relevant
- [x] Other (Added new project)

**Checklist:**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

**Additional info (if any):**

Consider this submission under hackoctoberfest'22.

### CODE REVIEW

**Comment by varunKT001** [comment]
@ravish036 

Is it a chrome extension?

**Comment by ravish036** [comment]
@varunKT001 
No, but can be converted into an extension.

**Review by varunKT001 — CHANGES_REQUESTED** [review]
@ravish036 

Rename `popup.html` to `index.html`. I have mentioned everything in the contribution guide. Please go through it once.

**Comment by ravish036** [comment]
@varunKT001 
Done 👍🏻

**Review by varunKT001 — APPROVED** [review]
LGTM @ravish036 
Thanks for your contribution!

**Pull request merged**
